{
  "swagger": "2.0",
  "info": {
    "title": "IoTHubGDR API",
    "description": "API to manage iot hub connections.",
    "version": "2.0",
    "contact": {
      "name": "Jitsuin",
      "url": "https://www.jitsuin.com"
    }
  },
  "tags": [
    {
      "name": "IoTHubGDR"
    }
  ],
  "host": "docs.rkvst.com",
  "basePath": "/archivist/v2",
  "schemes": [
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/archivist/v2/iothubgdr": {
      "get": {
        "summary": "List IoTHub GDR connections.",
        "description": "Returns a list of IoTHub GDR connections",
        "operationId": "IoTHubGDR_ListIoTHubGDRConnections",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v2ListIoTHubGDRConnectionsResponse"
            }
          },
          "401": {
            "description": "Returned when the user is not authenticated to the system.",
            "schema": {}
          },
          "403": {
            "description": "Returned when the user is not authorized to view Event.",
            "schema": {}
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/googlerpcStatus"
            }
          }
        },
        "tags": [
          "IoTHubGDR"
        ]
      },
      "post": {
        "summary": "Create an IoTHub GDR connection.",
        "description": "Create an IoTHub GDR connection.",
        "operationId": "IoTHubGDR_CreateIoTHubGDRConnection",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v2OperationResponse"
            }
          },
          "401": {
            "description": "Returned when the user is not authenticated to the system.",
            "schema": {}
          },
          "403": {
            "description": "Returned when the user is not authorized to view Event.",
            "schema": {}
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/googlerpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v2CreateIoTHubGDRConnectionRequest"
            }
          }
        ],
        "tags": [
          "IoTHubGDR"
        ]
      }
    },
    "/archivist/v2/iothubgdr/{uuid}": {
      "get": {
        "summary": "Retrieve an IoTHub GDR connection.",
        "description": "Retrieve an IoTHub GDR connection.",
        "operationId": "IoTHubGDR_GetIoTHubGDRConnection",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v2OperationResponse"
            }
          },
          "401": {
            "description": "Returned when the user is not authenticated to the system.",
            "schema": {}
          },
          "403": {
            "description": "Returned when the user is not authorized to view Event.",
            "schema": {}
          },
          "404": {
            "description": "Returned when the IotHubGDR does not exist.",
            "schema": {}
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/googlerpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "uuid",
            "description": "Specify the IoT Hub Grandfathering UUID where `iothubgdr/{uuid}` is the IoT Hub Grandfathering Identity e.g. `add30235-1424-4fda-840a-d5ef82c4c96f` from Identity `iothubgdr/add30235-1424-4fda-840a-d5ef82c4c96f`",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "IoTHubGDR"
        ]
      },
      "delete": {
        "summary": "Delete an IoTHub GDR connection.",
        "description": "Delete an IoTHub GDR connection.",
        "operationId": "IoTHubGDR_DeleteIoTHubGDRConnection",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "properties": {}
            }
          },
          "401": {
            "description": "Returned when the user is not authenticated to the system.",
            "schema": {}
          },
          "403": {
            "description": "Returned when the user is not authorized to view Event.",
            "schema": {}
          },
          "404": {
            "description": "Returned when the IotHubGDR does not exist.",
            "schema": {}
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/googlerpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "uuid",
            "description": "Specify the IoT Hub Grandfathering UUID where `iothubgdr/{uuid}` is the IoT Hub Grandfathering Identity e.g. `add30235-1424-4fda-840a-d5ef82c4c96f` from Identity `iothubgdr/add30235-1424-4fda-840a-d5ef82c4c96f`",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "IoTHubGDR"
        ]
      }
    },
    "/archivist/v2/iothubgdr/{uuid}:cancel": {
      "post": {
        "summary": "Cancel an IoTHub GDR connection.",
        "description": "Cancel an IoTHub GDR connection.",
        "operationId": "IoTHubGDR_CancelIoTHubGDRConnection",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v2OperationResponse"
            }
          },
          "401": {
            "description": "Returned when the user is not authenticated to the system.",
            "schema": {}
          },
          "403": {
            "description": "Returned when the user is not authorized to view Event.",
            "schema": {}
          },
          "404": {
            "description": "Returned when the IotHubGDR does not exist.",
            "schema": {}
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/googlerpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "uuid",
            "description": "Specify the IoT Hub Grandfathering UUID where `iothubgdr/{uuid}` is the IoT Hub Grandfathering Identity e.g. `add30235-1424-4fda-840a-d5ef82c4c96f` from Identity `iothubgdr/add30235-1424-4fda-840a-d5ef82c4c96f`",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "IoTHubGDR"
        ]
      }
    }
  },
  "definitions": {
    "googlerpcStatus": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "details": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/protobufAny"
          }
        }
      }
    },
    "protobufAny": {
      "type": "object",
      "properties": {
        "type_url": {
          "type": "string"
        },
        "value": {
          "type": "string",
          "format": "byte"
        }
      }
    },
    "v2CreateIoTHubGDRConnectionRequest": {
      "type": "object",
      "example": {
        "display_name": "My Company IoT Hub",
        "secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "arc_home_location_identity": "locations/25f812d3-10ab-4451-8bd1-fb02454c9361"
      },
      "properties": {
        "display_name": {
          "type": "string",
          "description": "display name for this import",
          "maxLength": 1024
        },
        "secret": {
          "type": "string",
          "description": "secret used to connect to IoT Hub",
          "maxLength": 1024
        },
        "arc_home_location_identity": {
          "type": "string",
          "description": "Identity of location` as in `locations/add30235-1424-4fda-840a-d5ef82c4c96f`",
          "readOnly": true
        }
      },
      "description": "Create IoTHubGDR import"
    },
    "v2ListIoTHubGDRConnectionsResponse": {
      "type": "object",
      "example": [
        {
          "identity": "iothubgdr/14e7f1c2-23ba-5642-9ce0-ffc3563da452",
          "done": "true",
          "timestamp_accepted": "2019-11-27T14:44:19Z",
          "timestamp_finished": "2019-11-28T14:45:29Z",
          "result": {
            "display_name": "My Company IoT Hub",
            "number_assets_imported": 66,
            "arc_home_location_identity": "locations/25f812d3-10ab-4451-8bd1-fb02454c9361",
            "status": "STATUS_FINISHED"
          }
        },
        {
          "identity": "iothubgdr/25f8a2d3-34cb-4531-8dc1-dcc4524db521",
          "done": "true",
          "timestamp_accepted": "2019-11-29T12:54:56Z",
          "timestamp_finished": "2019-11-30T09:15:39Z",
          "result": {
            "display_name": "My Other Company IoT Hub",
            "number_assets_imported": 42,
            "arc_home_location_identity": "locations/15bb2ca4-21bc-5427-778c-d2ab6ddc1452",
            "status": "STATUS_CANCELLED"
          }
        }
      ],
      "properties": {
        "operations": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/v2OperationResponse"
          }
        }
      },
      "description": "Long running operation"
    },
    "v2OperationError": {
      "type": "object",
      "example": {
        "display_name": "My Company IoT Hub",
        "number_assets_imported": 66,
        "arc_home_location_identity": "locations/25f812d3-10ab-4451-8bd1-fb02454c9361",
        "error_message": "could not connect to IoT Hub"
      },
      "properties": {
        "display_name": {
          "type": "string",
          "description": "display name for this import",
          "maxLength": 1024
        },
        "number_assets_imported": {
          "type": "string",
          "format": "int64",
          "description": "number of Assets imported"
        },
        "arc_home_location_identity": {
          "type": "string",
          "description": "identity of a location wo which to add the assets"
        },
        "error_message": {
          "type": "string",
          "description": "error message",
          "maxLength": 1024
        }
      },
      "description": "Result of an import that failed"
    },
    "v2OperationResponse": {
      "type": "object",
      "example": {
        "identity": "iothubgdr/14e7f1c2-23ba-5642-9ce0-ffc3563da452",
        "done": "true",
        "timestamp_accepted": "2019-11-27T14:44:19Z",
        "timestamp_finished": "2019-11-28T14:45:29Z",
        "result": {
          "display_name": "My Company IoT Hub",
          "number_assets_imported": 66,
          "arc_home_location_identity": "locations/25f812d3-10ab-4451-8bd1-fb02454c9361",
          "status": "STATUS_FINISHED"
        }
      },
      "properties": {
        "identity": {
          "type": "string",
          "description": "unique identity of this operations"
        },
        "done": {
          "type": "boolean",
          "description": "indicates if import is still running"
        },
        "timestamp_accepted": {
          "type": "string",
          "format": "date-time",
          "description": "time when import has been accepted by the API"
        },
        "timestamp_finished": {
          "type": "string",
          "format": "date-time",
          "description": "time import finished"
        },
        "result": {
          "$ref": "#/definitions/v2OperationResult"
        },
        "error": {
          "$ref": "#/definitions/v2OperationError"
        }
      },
      "description": "Long running operation"
    },
    "v2OperationResult": {
      "type": "object",
      "example": {
        "display_name": "My Company IoT Hub",
        "number_assets_imported": 66,
        "arc_home_location_identity": "locations/25f812d3-10ab-4451-8bd1-fb02454c9361",
        "status": "STATUS_FINISHED"
      },
      "properties": {
        "display_name": {
          "type": "string",
          "description": "display name for this import",
          "maxLength": 1024
        },
        "number_assets_imported": {
          "type": "string",
          "format": "int64",
          "description": "number of Assets imported"
        },
        "arc_home_location_identity": {
          "type": "string",
          "description": "identity of a location to set when adding the assets"
        },
        "status": {
          "$ref": "#/definitions/v2OperationResultStatus",
          "description": "status of the import"
        }
      },
      "description": "Result of the import - in progress or completed succefully"
    },
    "v2OperationResultStatus": {
      "type": "string",
      "enum": [
        "STATUS_UNSPECIFIED",
        "STATUS_PENDING",
        "STATUS_INPROGRESS",
        "STATUS_FINISHED",
        "STATUS_CANCELLED"
      ],
      "default": "STATUS_UNSPECIFIED"
    }
  }
}
